---
title: "Two-stroke dirt-bikes data exploration"
output: html_notebook
---



```{r, collapse=TRUE}
# Number of listings by Model
table(df$Bike)[order(-table(df$Bike))]
# Number of listings by Year
table(df$Year)[order(-table(df$Year))]
# Number of listings by State
table(df$State)[order(-table(df$State))]
# Number of listings by Source
table(df$Source)[order(-table(df$Source))]
```

```{r, include=FALSE, echo=FALSE}
hist(df$Price,
     xlab = "Price (USD)",
     main = "Histogram of Asking Price")
```

The following histogram shows that YZ125 are less common than YZ250 and YZ125 are priced about $500 lower than YZ250 on average.

```{r}
x1 <- df$Price[df$Bike=="YZ125" & df$Year >= 2005 & df$Year <= 2016]
x2 <- df$Price[df$Bike=="YZ250" & df$Year >= 2005 & df$Year <= 2016]

par(mfrow=c(1,2))

hist(x1, 
     xlab = "Price (USD)",
     main = "Asking price for YZ125\n2005-2016 models")

hist(x2, 
     xlab = "Price (USD)",
     main = "Asking price for YZ250\n2005-2016 models")
```
```{r}
x1 <- df$Price[df$Bike=="YZ125" & df$Year >= 2005 & df$Year <= 2016]
x2 <- df$Price[df$Bike=="YZ250" & df$Year >= 2005 & df$Year <= 2016]

par(mfrow=c(1,2))

hist(x1, 
     xlab = "Price (USD)",
     main = "Asking price for YZ125\n2005-2016 models")

hist(x2, 
     xlab = "Price (USD)",
     main = "Asking price for YZ250\n2005-2016 models")
```


```{r}
frequencyTable <- data.frame(table(df$Bike))
names(frequencyTable)[1] <- "Bike"

df <- left_join(df,frequencyTable)

df_subset <- df[df$Freq >= 10,]

plot_ly(df_subset, 
        x = ~Year, 
        y = ~Price, 
        type = 'scatter', 
        mode = 'markers',
        text = ~paste('Location: ',paste(Location,State,sep=" ,")), 
        color = ~as.factor(Bike))
```